version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 10
  target-branch: [react, master]
